# YieldSync Aggregator Configuration
# This configuration file defines all the settings for the YieldSync aggregator

# Environment: 'production' only prints info and above. 'development' also prints debug
environment: production

# Ethereum configuration
eth_rpc_url: "https://eth-mainnet.g.alchemy.com/v2/YOUR_API_KEY"
eth_ws_url: "wss://eth-mainnet.g.alchemy.com/v2/YOUR_API_KEY"
private_key: "0x1234567890123456789012345678901234567890123456789012345678901234"
address: "0x1234567890123456789012345678901234567890"

# Chain configuration
chain_id: 1

# Aggregator configuration
aggregator:
  server_ip_port_addr: "localhost:8090"
  enable_metrics: true
  metrics_ip_port_addr: "localhost:9090"
  enable_node_api: true
  node_api_ip_port_addr: "localhost:9091"

# EigenLayer configuration
eigenlayer:
  delegation_manager_address: "0x39053D51B77DC0d36036Fc1fCc8Cb819df8Ef37A"
  service_manager_address: "0x1234567890123456789012345678901234567890"
  task_manager_address: "0x1234567890123456789012345678901234567890"
  registry_coordinator_address: "0x1234567890123456789012345678901234567890"
  operator_state_retriever_address: "0x1234567890123456789012345678901234567890"
  rewards_coordinator_address: "0x1234567890123456789012345678901234567890"
  allocation_manager_address: "0x1234567890123456789012345678901234567890"

# Logger configuration
logger:
  level: "info"
  format: "json"

# Database configuration
database:
  driver: "sqlite3"
  source: "./data/aggregator.db"

# Monitoring configuration
monitoring:
  enable_prometheus: true
  prometheus_port: 9090
  enable_grafana: true
  grafana_port: 3000

# Task configuration
task:
  response_window_blocks: 100
  challenge_window_blocks: 100
  max_tasks_per_block: 10

# BLS aggregation configuration
bls_aggregation:
  quorum_threshold_percentage: 50
  max_operators_per_quorum: 100
  signature_timeout: "30s"

# RPC server configuration
rpc_server:
  max_concurrent_requests: 100
  request_timeout: "30s"
  max_request_size: "10MB"
